//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationManagementFootballLeague.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BaseSZLPEntities : DbContext
    {
        public BaseSZLPEntities()
            : base("name=BaseSZLPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<COMMENTS> COMMENTS { get; set; }
        public DbSet<EVENT> EVENT { get; set; }
        public DbSet<MATCH> MATCH { get; set; }
        public DbSet<NEWS> NEWS { get; set; }
        public DbSet<PLAYER> PLAYER { get; set; }
        public DbSet<STAFF> STAFF { get; set; }
        public DbSet<STAFF_IN_MATCHES> STAFF_IN_MATCHES { get; set; }
        public DbSet<STAFF_IN_TEAMS> STAFF_IN_TEAMS { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TEAM> TEAM { get; set; }
        public DbSet<TEAMS_IN_MATCH> TEAMS_IN_MATCH { get; set; }
        public DbSet<TEAMS_IN_MATCH_PLAYERS_ALLOCATION> TEAMS_IN_MATCH_PLAYERS_ALLOCATION { get; set; }
        public DbSet<UserProfile> UserProfile { get; set; }
        public DbSet<webpages_Membership> webpages_Membership { get; set; }
        public DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public DbSet<webpages_Roles> webpages_Roles { get; set; }
    }
}
