//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationManagementFootballLeague.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMENTS
    {
        public int ID_comment { get; set; }
        public string userIP { get; set; }
        public string text { get; set; }
        public string date { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ID_news { get; set; }
    
        public virtual NEWS NEWS { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
