//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationManagementFootballLeague.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATCH
    {
        public MATCH()
        {
            this.STAFF_IN_MATCHES = new HashSet<STAFF_IN_MATCHES>();
            this.TEAMS_IN_MATCH = new HashSet<TEAMS_IN_MATCH>();
        }
    
        public int ID_match { get; set; }
        public int durationOfMatch { get; set; }
        public string dateOfMatch { get; set; }
        public int numberOfPlayers { get; set; }
        public Nullable<int> round { get; set; }
        public Nullable<int> hostScore { get; set; }
        public Nullable<int> guestScore { get; set; }
        public string timeOfMatch { get; set; }
    
        public virtual EVENT EVENT { get; set; }
        public virtual ICollection<STAFF_IN_MATCHES> STAFF_IN_MATCHES { get; set; }
        public virtual ICollection<TEAMS_IN_MATCH> TEAMS_IN_MATCH { get; set; }
    }
}
