//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationManagementFootballLeague.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAYER
    {
        public PLAYER()
        {
            this.EVENT = new HashSet<EVENT>();
            this.TEAMS_IN_MATCH_PLAYERS_ALLOCATION = new HashSet<TEAMS_IN_MATCH_PLAYERS_ALLOCATION>();
        }
    
        public int ID_player { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string dateOfBirth { get; set; }
        public Nullable<int> number { get; set; }
        public string position { get; set; }
        public string dateOfRegistration { get; set; }
        public Nullable<bool> isActivePlayer { get; set; }
        public string picture { get; set; }
        public Nullable<int> numberOfGoals { get; set; }
        public Nullable<int> timeOnThePitch { get; set; }
        public Nullable<int> numberOfYellowCards { get; set; }
        public Nullable<int> numberOfRedCards { get; set; }
        public Nullable<int> numberOfAssists { get; set; }
        public Nullable<int> ID_team { get; set; }
    
        public virtual ICollection<EVENT> EVENT { get; set; }
        public virtual ICollection<TEAMS_IN_MATCH_PLAYERS_ALLOCATION> TEAMS_IN_MATCH_PLAYERS_ALLOCATION { get; set; }
        public virtual TEAM TEAM { get; set; }
    }
}
