//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationManagementFootballLeague.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF
    {
        public STAFF()
        {
            this.STAFF_IN_MATCHES = new HashSet<STAFF_IN_MATCHES>();
            this.STAFF_IN_TEAMS = new HashSet<STAFF_IN_TEAMS>();
        }
    
        public int ID_staff { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public Nullable<bool> isReferee { get; set; }
        public string role { get; set; }
    
        public virtual ICollection<STAFF_IN_MATCHES> STAFF_IN_MATCHES { get; set; }
        public virtual ICollection<STAFF_IN_TEAMS> STAFF_IN_TEAMS { get; set; }
    }
}
