//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationManagementFootballLeague.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEAMS_IN_MATCH_PLAYERS_ALLOCATION
    {
        public int ID_player { get; set; }
        public int ID_teamComposition { get; set; }
    
        public virtual PLAYER PLAYER { get; set; }
    }
}
