//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationManagementFootballLeague.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEAM
    {
        public TEAM()
        {
            this.NEWS = new HashSet<NEWS>();
            this.PLAYER = new HashSet<PLAYER>();
            this.STAFF_IN_TEAMS = new HashSet<STAFF_IN_TEAMS>();
            this.TEAMS_IN_MATCH = new HashSet<TEAMS_IN_MATCH>();
        }
    
        public int ID_team { get; set; }
        public string name { get; set; }
        public string logo { get; set; }
        public string mail { get; set; }
        public string street { get; set; }
        public Nullable<int> apartmentNumber { get; set; }
        public string zipCode { get; set; }
        public string city { get; set; }
        public string region { get; set; }
        public string phoneNumber { get; set; }
        public string faxNumber { get; set; }
        public string foundationDate { get; set; }
        public string ageCategory { get; set; }
        public string description { get; set; }
        public string www { get; set; }
        public Nullable<int> points { get; set; }
        public Nullable<int> numberOfWins { get; set; }
        public Nullable<int> numberOfDraws { get; set; }
        public Nullable<int> numberOfLosses { get; set; }
        public Nullable<int> numberOfGoalsScored { get; set; }
        public Nullable<int> numberOfGoalsLost { get; set; }
        public Nullable<int> numberOfMatches { get; set; }
        public string league { get; set; }
    
        public virtual ICollection<NEWS> NEWS { get; set; }
        public virtual ICollection<PLAYER> PLAYER { get; set; }
        public virtual ICollection<STAFF_IN_TEAMS> STAFF_IN_TEAMS { get; set; }
        public virtual ICollection<TEAMS_IN_MATCH> TEAMS_IN_MATCH { get; set; }
    }
}
